name: バグレポート（日本語、Java版）
description: モダーンフォントパック のバグレポートを提出する
title: "[Bug] "
labels: ["Bug", "In triage", "Java Edition"]
body:
  - type: markdown
    attributes:
      value: |
        このバグレポートにご記入いただき、ありがとうございます。
  - type: textarea
    id: what-happened
    attributes:
      label: バグの説明
      description: 発生したバグ情報を詳しく説明してください。
      placeholder: 発生したバグを教えてください。
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 再現する手順
      description: バグを引き起こしたステップを説明してください。
      placeholder: |
        1. ...
        2. ...
        3. ...
      render: bash
    validations:
      required: true
  - type: input
    id: expected-behavior
    attributes:
      label: 予想される動作
      description: 希望する効果について簡単に説明してください。
    validations:
      required: true
  - type: input
    id: actual-behavior
    attributes:
      label: 実際の動作
      description: 実際の結果について簡単に説明してください。
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: モダーンフォントパック バージョン
      description: 現在使用している モダーンフォントパック のバージョンは何ですか？（例：v919。リソースパックのタイトルに示されているバージョン番号から検出されます。使用しているバージョンがこちらにリストされていない場合、使用しているバージョンは古くなっています。最新バージョンに更新して、バグの再現を再試行してください。）
      options:
        - v119
        - v219
        - v319
        - v419
        - v519
        - v619
        - v719
        - v819
        - v919
        - v1019
    validations:
      required: true
  - type: dropdown
    id: game-version
    attributes:
      label: プレイしているゲームバージョンは何ですか？
      description: （使用しているバージョンがこちらにリストされていない場合、使用しているバージョンはサポートされていません。サポートされているバージョンを使用して、バグの再現を再試行してください。）
      options:
        - 1.19.3
        - 1.19.2
        - 1.19.1
        - 1.19
        - 1.18.2
        - 1.18.1
        - 1.18
        - 1.17.1
        - 1.17
        - 1.16.5
        - 1.16.4
        - 1.16.3
        - 1.16.2
        - 1.16.1
        - 1.16
        - 1.15.2
        - 1.15.1
        - 1.15
        - 1.14.4
        - 1.14.3
        - 1.14.2
        - 1.14.1
        - 1.14
        - 1.13.2
        - 1.13.1
        - 1.13
        - 1.12.2
        - 1.12.1
        - 1.12
        - 1.11.2
        - 1.11.1
        - 1.11
        - 1.10.2
        - 1.10.1
        - 1.10
        - 1.9.4
        - 1.9.3
        - 1.9.2
        - 1.9.1
        - 1.9
        - 1.8.9
        - 1.8.8
        - 1.8.7
        - 1.8.6
        - 1.8.5
        - 1.8.4
        - 1.8.3
        - 1.8.2
        - 1.8.1
        - 1.8
        - 1.7.10
        - 1.7.9
        - 1.7.8
        - 1.7.7
        - 1.7.6
        - 1.7.5
        - 1.7.4
        - 1.7.2
        - 1.6.4
        - 1.6.2
        - 1.6.1
    validations:
      required: true
  - type: dropdown
    id: snapshot
    attributes:
      label: スナップショットバージョンで使用されますか？
      options: 
        - はい
        - いいえ
    validations:
      required: true
  - type: dropdown
    id: snapshot-version
    attributes:
      label: スナップショットバージョンで使用する場合は、スナップショットバージョンの名前を入力してください。
    validations:
      required: false
  - type: dropdown
    id: operating-system
    attributes:
      label: 使用しているデバイスのシステムは何ですか？
      options:
        - Windows
        - Mac OS
        - Linux
        - その他
    validations:
      required: false
  - type: textarea
    id: additional-information
    attributes:
      label: 追加情報
      description: ゲームがクラッシュした場合は、必ずゲームログまたはクラッシュレポートをこちらに提供してください。
      placeholder: |
        ...
      render: bash
    validations:
      required: false