name: Bug Report (English, Java Edition)
description: Submit Modern Font Pack bug report
title: "[Bug] "
labels: ["Bug", "Pending", "Java Edition"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: Description of the Bug
      description: Please describe in detail the bug information that occurred.
      placeholder: Tell us what bug occurred.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Please describe the step that triggered the bug.
      placeholder: |
        1. ...
        2. ...
        3. ...
      render: bash
    validations:
      required: true
  - type: input
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Please give a brief description of the desired effect.
    validations:
      required: true
  - type: input
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Please give a brief description of the actual result.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Modern Font Pack Version
      description: What version of Modern Font Pack are you currently using? (e.g. v921, found from the version number indicated in the title of the resource pack. If the version you are using is not listed here, the version you are using is out of date. Please update to the latest version and try to reproduce the bug again.)
      options:
        - v021
        - v121
        - v221
        - v321
        - v421
        - v521
        - v621
        - v721
        - v821
        - v921
        - v1021
    validations:
      required: true
  - type: input
    id: game-version
    attributes:
      label: What is the game version you are playing?
      description: Please enter the affected game version(s).
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: What is the system of the device you are using?
      options:
        - Windows
        - Mac OS
        - Linux
        - Other
    validations:
      required: false
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: If the game crashes, be sure to provide the game log or crash report here.
      placeholder: |
        ...
      render: bash
    validations:
      required: false