name: Bug Report (English, Bedrock Edition)
description: Submit Modern Font Pack bug report
title: "[Bug] "
labels: ["Bug", "In triage", "Bedrock Edition"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: Description of the Bug
      description: Please describe in detail the bug information that occurred.
      placeholder: Tell us what bug occurred.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Please describe the step that triggered the bug.
      placeholder: |
        1. ...
        2. ...
        3. ...
      render: bash
    validations:
      required: true
  - type: input
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Please give a brief description of the desired effect.
    validations:
      required: true
  - type: input
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Please give a brief description of the actual result.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Modern Font Pack Version
      description: What version of Modern Font Pack are you currently using? (e.g. v221, found from the version number indicated in the title of the resource pack. If the version you are using is not listed here, the version you are using is out of date. Please update to the latest version and try to reproduce the bug again.)
      options:
        - v121
        - v221
    validations:
      required: true
  - type: input
    id: game-version
    attributes:
      label: What is the game version you are playing?
      description: Please enter the affected game version(s).
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: What is the system of the device you are using?
      options:
        - Windows
        - iOS
        - Android
        - Other
    validations:
      required: false