blank_issues_enabled: true
contact_links:
  - name: Yuta's Game World Discord Community
    url: https://discord.gg/tqzdEaBAcn
    about: Join the Yuta's Game World Discord community, where you can ask questions or discuss chat, etc...